@startuml plat

class PlatDocument {
  -location
  -pages
  +plat_path
  +image_directory
  +ocr_output_path
  +__post_init__()
  +write_ocr_text()
  +process_file()
}

class PlatPage {
  -file
  -page_num
  -image_data
  -image_directory
  +image_path
  +image_path.setter
  +__post_init__()
  +write_images()
  +image_string
}

class PDFHandler {
  +process_pdf()
}

PlatDocument "1" -- "many" PlatPage : contains
PlatDocument "1" -- "1" PDFHandler : uses

@enduml